#!/usr/bin/env bash

wait_with_spinner_loading() {
    # USAGE		NOTE: the "&" at the end of the line is crucial
    # task & <---'
    # wait_with_spinner_loading "TASK'S NAME"

    local NC='\033[0m' # No Color
    local BGREEN='\033[1;32m'
    local BYELLOW='\033[1;33m'

    local spin='-\|/'
    local i=0
    local pid=$!
    local process_title=$1

    while kill -0 $pid &>/dev/null; do
        local i=$(((i + 1) % 4))
        printf "\r%s%*s[${BYELLOW} ${spin:$i:1} ${NC}]" "$process_title" "$((40 - ${#process_title}))"
        sleep 0.4
    done
    printf "\r%s%*s${BGREEN}[ ✓ ]${NC}\n" "$process_title" "$((40 - ${#process_title}))"
}
